# Spring properties
spring:
  application:
     name: customer-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


# HTTP Server
server:
  port: 2223   # HTTP (Tomcat) port

apacheHttpClient:
  maxConnections: 1000
  maxConnectionsPerHost: 1000
  connectTimeoutMillis: 5000
  readTimeoutMillis: 60000
  logLevel: Full  # None/Basic/Headers/Full
